### ISSUE TITLE
[feat. request] Add lookahead to dynamic processors?

### ISSUE THREAD

**Issue by pms967** [chkhld/jsfx#2]
Hi, 

first of all, thank you for your nice work.

I was wondering if it would be possible to add an optional/adjustable "look-ahead" function to the gate/expander (and perhaps to compressors, too).

**Comment by chkhld** [comment]
Thank you. :)

Certainly, it would be possible to add that, and I know how to, but I doubt I will actually do that, at least anytime soon.

Unfortunately, EEL (the language behind JSFX plugins) is quite nasty and enfuriating when it comes to handling arrays (at least for me), and messing with arrays would be required to buffer the lookahead samples. I've played around with rotating buffers in JSFX before (drop a sample, add a new one) and it's possible, but either it's very CPU intensive if done simply, or it's very tedious to set up and maintain a ring buffer, let alone for multiple channels.

Maybe someday during refactoring, who knows, but I won't promise. :)
